### ISSUE TITLE
the link to ctgrind is no longer valid

### ISSUE THREAD

**Issue by surechen** [rust-secure-code/projects#13]
Hi, the list is fantastic. I found that the link(https://github.com/RustCrypto/utils/tree/master/ctgrind) to ctgrind is no longer valid. What is the current status of this project? Or are there any other options?

**Comment by Shnatsel** [comment]
https://www.reparaz.net/oscar/misc/dudect.html lists some variants of it as well as some alternatives.

**Comment by surechen** [comment]
Thank you very much, very helpful to me.

**Comment by surechen** [comment]
> https://www.reparaz.net/oscar/misc/dudect.html lists some variants of it as well as some alternatives.

Thank you very much, very helpful to me.
