### ISSUE TITLE
Crate adoption or suggest migration

### ISSUE THREAD

**Issue by WildCryptoFox** [rust-secure-code/projects#18]
I no longer wish to maintain 4 crates which have accumulated dependents. Instead of transferring ownership over the name to the first person who shows interest in a project, should I publish a breaking version change which erases all functionality and announces the crate is archived, then suggest migrating to or creating a new fork. Listing known alternatives if they exist.

What do you think?

Alternatively I would be happy to transfer the crates to any member of this organization with implicit trust.

The crates in question have 11, 1, 18, 1, dependents respectively. The nature of `alloc_counter` and `criterion-cycles-per-byte` tend towards security contexts, notably cryptography.

https://crates.io/crates/alloc_counter/reverse_dependencies
https://crates.io/crates/alloc_counter_macro/reverse_dependencies
https://crates.io/crates/criterion-cycles-per-byte/reverse_dependencies
https://crates.io/crates/wrapped_enum/reverse_dependencies

**Comment by WildCryptoFox** [comment]
The single other contributor for `alloc-counter` is open to maintaining a fork, if you don't adopt it.

**Comment by Shnatsel** [comment]
Hello! Thank you for the consideration given to the fate of the dependents!

Instead of publishing a new version with the functionality removed, I suggest updating the README with the maintenance status. We could also publish an advisory about the maintenance status and suggest alternatives (if any) via https://github.com/rustsec/advisory-db

Generally the Secure Code WG doesn't take over maintenance. However, I suggest reaching out to https://github.com/rust-bus - their mission is pretty similar.

**Comment by Shnatsel** [comment]
Reaching out to the users of your crate and seeing if they would like to take over maintenance could be a good idea.

**Comment by WildCryptoFox** [comment]
Thanks for the feedback.

I've decided to keep things simple and transfer ownership for the 3 main crates to a contributor back when `alloc-counter` was active and to the user who reported the version conflict for `criterion-cycles-per-byte`; and call it a day. I will not be monitoring these crates and will trust these users to behave. If you have a set of crates you watch for changes, maybe add the 3 crates. If they change, it will probably be rare to adjust for version compatibility or similar minor changes.

https://crates.io/crates/alloc_counter
https://crates.io/crates/alloc_counter_macro
https://crates.io/crates/criterion-cycles-per-byte
