### ISSUE TITLE
Mention cargo-deny

### ISSUE THREAD

**Issue by djc** [rust-secure-code/projects#7]
Since cargo-deny also provides vulnerability checking (I think it uses the same underlying code as cargo-audit) it would be nice to mention it here. (Of course it does some more things which might also be mentioned somehow.) It seems like a nice unified solution.

**Comment by ralpha** [comment]
+1 for [cargo-deny](https://github.com/EmbarkStudios/cargo-deny). Also good to have a CI job.

**Comment by Shnatsel** [comment]
PRs are welcome!

**Comment by ralpha** [comment]
Added a general outline of what it does. Feedback is welcome.
